### ISSUE TITLE
pip doesn't respect `requires`

### ISSUE THREAD

**Issue by cmutel** [rasbt/pyprind#11]
Hi Sebastien-

Thanks for this awesome library.

Pip 1.5.6 and pip 6.1.1 don't respect `requires` in setup.py (Tried on 2.7 and 3.4). It seems like this needs to be `install_requires` to get psutil included as a dependency when using pip to install.

**Comment by rasbt** [comment]
Thanks for letting me know. I looked a little bit into this `requires` vs. `install_requires`, pip, setuptools and distutils... Python packaging still seems to be a little bit messy ;).  

I decided to remove the `requires` and added a `requirements.txt` file, plus I added a note in the installation section of the Readme since `psutil` is not really required to run pyprind except for the monitoring functionality. So people can optionally install it via `pip pyprind install -r requirements.txt` if they want to.
